<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="de_DE">
<context>
    <name>ControlPanel</name>
    <message>
        <location filename="../../ui/control_panel.py" line="14"/>
        <source>Connect</source>
        <translation>Verbinden</translation>
    </message>
    <message>
        <location filename="../../ui/control_panel.py" line="18"/>
        <source>Disconnect</source>
        <translation>Trennen</translation>
    </message>
    <message>
        <location filename="../../ui/control_panel.py" line="22"/>
        <source>Import Config</source>
        <translation>Konfig. importieren</translation>
    </message>
    <message>
        <location filename="../../ui/control_panel.py" line="25"/>
        <source>Delete Config</source>
        <translation>Konfig. löschen</translation>
    </message>
</context>
<context>
    <name>CredentialsDialog</name>
    <message>
        <location filename="../../credentials_dialog.py" line="22"/>
        <source>Enter Credentials</source>
        <translation>Anmeldedaten eingeben</translation>
    </message>
    <message>
        <location filename="../../credentials_dialog.py" line="27"/>
        <source>Please enter your credentials for:</source>
        <translation>Bitte geben Sie Ihre Anmeldedaten ein für:</translation>
    </message>
    <message>
        <location filename="../../credentials_dialog.py" line="32"/>
        <source>Username:</source>
        <translation>Benutzername:</translation>
    </message>
    <message>
        <location filename="../../credentials_dialog.py" line="37"/>
        <source>Password:</source>
        <translation>Passwort:</translation>
    </message>
    <message>
        <location filename="../../credentials_dialog.py" line="44"/>
        <source>Show Password</source>
        <translation>Passwort anzeigen</translation>
    </message>
    <message>
        <location filename="../../credentials_dialog.py" line="48"/>
        <source>Save for this configuration</source>
        <translation>Für diese Konfiguration speichern</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="../../main.py" line="90"/>
        <source>Show/Hide</source>
        <translation>Anzeigen/Verstecken</translation>
    </message>
    <message>
        <location filename="../../main.py" line="94"/>
        <source>Quit</source>
        <translation>Beenden</translation>
    </message>
    <message>
        <location filename="../../main.py" line="111"/>
        <source>Found</source>
        <translation>Gefunden</translation>
    </message>
    <message>
        <location filename="../../main.py" line="111"/>
        <source>configurations</source>
        <translation>Konfigurationen</translation>
    </message>
    <message>
        <location filename="../../main.py" line="140"/>
        <source>Successfully connected to</source>
        <translation>Erfolgreich verbunden mit</translation>
    </message>
    <message>
        <location filename="../../main.py" line="141"/>
        <source>Connected</source>
        <translation>Verbunden</translation>
    </message>
    <message>
        <location filename="../../main.py" line="145"/>
        <source>Connection has been disconnected.</source>
        <translation>Verbindung wurde getrennt.</translation>
    </message>
    <message>
        <location filename="../../main.py" line="148"/>
        <source>Connection Error</source>
        <translation>Verbindungsfehler</translation>
    </message>
    <message>
        <location filename="../../main.py" line="152"/>
        <source>No configuration selected.</source>
        <translation>Keine Konfiguration ausgewählt.</translation>
    </message>
    <message>
        <location filename="../../main.py" line="156"/>
        <source>Starting connection for</source>
        <translation>Starte Verbindung für</translation>
    </message>
    <message>
        <location filename="../../main.py" line="169"/>
        <source>Credentials required.</source>
        <translation>Anmeldedaten erforderlich.</translation>
    </message>
    <message>
        <location filename="../../main.py" line="188"/>
        <source>Authentication cancelled by user.</source>
        <translation>Authentifizierung durch Benutzer abgebrochen.</translation>
    </message>
    <message>
        <location filename="../../main.py" line="192"/>
        <source>Disconnecting</source>
        <translation>Verbindung wird getrennt</translation>
    </message>
    <message>
        <location filename="../../main.py" line="210"/>
        <source>Confirm Deletion</source>
        <translation>Löschen bestätigen</translation>
    </message>
    <message>
        <location filename="../../main.py" line="211"/>
        <source>Are you sure you want to delete</source>
        <translation>Sind Sie sicher, dass Sie</translation>
    </message>
    <message>
        <location filename="../../main.py" line="220"/>
        <source>deleted</source>
        <translation>gelöscht</translation>
    </message>
    <message>
        <location filename="../../main.py" line="242"/>
        <source>Permission Error</source>
        <translation>Berechtigungsfehler</translation>
    </message>
    <message>
        <location filename="../../main.py" line="243"/>
        <source>Sudo permissions for the helper script are not configured correctly.
Please run the install script (install.sh) to set up the required permissions.
The application will not be able to connect to VPNs.</source>
        <translation>Die Sudo-Berechtigungen für das Hilfsskript sind nicht korrekt konfiguriert.
Bitte führen Sie das Installationsskript (install.sh) aus, um die erforderlichen Berechtigungen einzurichten.
Die Anwendung kann keine VPN-Verbindungen herstellen.</translation>
    </message>
    <message>
        <location filename="../../main.py" line="262"/>
        <source>Confirm Exit</source>
        <translation>Beenden bestätigen</translation>
    </message>
    <message>
        <location filename="../../main.py" line="263"/>
        <source>A VPN connection is active. Do you want to disconnect and exit?</source>
        <translation>Eine VPN-Verbindung ist aktiv. Möchten Sie die Verbindung trennen und beenden?</translation>
    </message>
    <message>
        <location filename="../../main.py" line="147"/>
        <source>Error</source>
        <translation>Fehler</translation>
    </message>
    <message>
        <location filename="../../main.py" line="199"/>
        <source>Configuration successfully imported.</source>
        <translation>Konfiguration erfolgreich importiert.</translation>
    </message>
    <message>
        <location filename="../../main.py" line="202"/>
        <source>Failed to import configuration</source>
        <translation>Import der Konfiguration fehlgeschlagen</translation>
    </message>
    <message>
        <location filename="../../main.py" line="203"/>
        <source>Error importing configuration</source>
        <translation>Fehler beim Import der Konfiguration</translation>
    </message>
    <message>
        <location filename="../../main.py" line="208"/>
        <source>Delete Error</source>
        <translation>Fehler beim Löschen</translation>
    </message>
    <message>
        <location filename="../../main.py" line="208"/>
        <source>This configuration cannot be deleted.</source>
        <translation>Diese Konfiguration kann nicht gelöscht werden.</translation>
    </message>
    <message>
        <location filename="../../main.py" line="219"/>
        <source>Configuration</source>
        <translation>Konfiguration</translation>
    </message>
    <message>
        <location filename="../../main.py" line="226"/>
        <source>Failed to delete configuration</source>
        <translation>Löschen der Konfiguration fehlgeschlagen</translation>
    </message>
    <message>
        <location filename="../../main.py" line="227"/>
        <source>Error deleting configuration</source>
        <translation>Fehler beim Löschen der Konfiguration</translation>
    </message>
    <message>
        <location filename="../../main.py" line="165"/>
        <source>Configuration not found:</source>
        <translation type="unfinished">Konfiguration nicht gefunden:</translation>
    </message>
</context>
</TS>